# config/meta.yml
meta_title: "Get all the best deals without searching for hours"
meta_description: "Scout finds you the best discounts based on your personal interests"
meta_image: "fb-photo.png" # Une image dans votre dossier app/assets/images/
